theme: jekyll-theme-cayman
title: VTEX Ads Documentation
description: Documentation for VTEX Ads Retail Media API
show_downloads: false
github:
  is_project_page: true

# URL and Base URL for GitHub Pages
url: "https://vtex.github.io"
baseurl: "/vtexads-api-docs"

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

source: ./
destination: ./_site
