%%{
  init: {
    "theme": "base",
    "themeVariables": {
        "primaryColor": "#FFF",
        "primaryBorderColor": "#F71963",
        "lineColor": "#F71963",
        "textColor": "#777",
        "actorTextColor": "#777"
    }
  }
}%%
sequenceDiagram
    participant Marketplace
    participant VTEXAds
    participant Seller

    Seller->>VTEXAds: Solicitar valor disponível para usar em Anúncios
    VTEXAds->>Marketplace: GET /checking_account?seller_id=SELLER_ID
    Marketplace-->>VTEXAds: 200 OK { "total": "1111.00" }
    VTEXAds-->>Seller: Mostrar valor

    Seller->>VTEXAds: Solicitar transferência de determinado valor para Anúncios
    VTEXAds->>Marketplace: POST /checking_account/transfer
    alt Sucesso Síncrono
        Marketplace-->>VTEXAds: 201 Created { "transaction_id": "...", "status": "success" }
    else Falha Síncrona
        Marketplace-->>VTEXAds: 400 Bad Request { "transaction_id": "...", "status": "failure", "message": "..." }
    else Webhook Assíncrono
        Marketplace-->>VTEXAds: 202 Accepted { "transaction_id": "...", "status": "processing" }
        Marketplace->>VTEXAds: POST /webhook/marketplace/transfers <br/>{ "transaction_id": "...", "status": "success/failure", ... }
        VTEXAds-->>Marketplace: 204 OK
    end
    VTEXAds-->>Seller: Confirmar se transferência foi sucesso ou falha
