%%{
  init: {
    "theme": "base",
    "themeVariables": {
        "primaryColor": "#FFF",
        "primaryBorderColor": "#F71963",
        "lineColor": "#F71963",
        "textColor": "#777",
        "actorTextColor": "#777"
    }
  }
}%%
sequenceDiagram
    participant Marketplace
    participant VTEXAds
    participant Seller

    Seller->>VTEXAds: Request to see amount available to use in ADs
    VTEXAds->>Marketplace: GET /checking_account?seller_id=SELLER_ID
    Marketplace-->>VTEXAds: 200 OK { "total": "1111.00" }
    VTEXAds-->>Seller: Show amount

    Seller->>VTEXAds: Request to transfer certain amount to ADs
    VTEXAds->>Marketplace: POST /checking_account/transfer
    alt Synchronous Success
        Marketplace-->>VTEXAds: 201 Created { "transaction_id": "...", "status": "success" }
    else Synchronous Failure
        Marketplace-->>VTEXAds: 400 Bad Request { "transaction_id": "...", "status": "failure", "message": "..." }
    else Asynchronous Webhook
        Marketplace-->>VTEXAds: 202 Accepted { "transaction_id": "...", "status": "processing" }
        Marketplace->>VTEXAds: POST /webhook/marketplace/transfers <br/>{ "transaction_id": "...", "status": "success/failure", ... }
        VTEXAds-->>Marketplace: 204 OK
    end
    VTEXAds-->>Seller: Confirm if transfer was success or fail